# Q1: Import numpy library

In [3]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [4]:
# write your code here ^_^
np.linspace(0,30,15)

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [5]:
# write your code here ^_^
a3D =  np.array(
    [
        [
            [1.1, 2.1,3.1],
            [4.1, 5.1,6.1]
        ],
        [
            [7.1, 8.1 , 9.1], 
            [10.1, 11.1,12.1]
        ]
    ])
a3D

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [6]:
# write your code here ^_^
print('type = ',type(a3D))
print('data type = ', a3D.dtype)
print('number of dimensions = ', a3D.ndim)
print('shape = ', a3D.shape)
print('size = ', a3D.size)

type =  <class 'numpy.ndarray'>
data type =  float64
number of dimensions =  3
shape =  (2, 2, 3)
size =  12


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [7]:
# write your code here ^_^

newArray=np.asarray(a3D).reshape((1,2,2 ,3 ))
print('number of dimensions = ', newArray.ndim)
print('shape = ', newArray.shape)
newArray

number of dimensions =  4
shape =  (1, 2, 2, 3)


array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [8]:
# write your code here ^_^
integer_array = newArray.astype(int) 
print (integer_array)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [90]:
# write your code here ^_^
for z in np.nditer(integer_array):
    print(z, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [20]:
# write your code here ^_^
integer_array[0:,1:2,0:1,1:2]
#integer_array[0,1,0,1]

array([[[[8]]]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [23]:
# write your code here ^_^
integer_array[0:,0:1,1:2,1:3]

array([[[[5, 6]]]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [92]:
# write your code here ^_^
x=np.where(integer_array == 8)
print(x)

(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [28]:
# write your code here ^_^
a=integer_array.reshape(1,2,3,2)
a

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [87]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
print('arr1 = ',arr1)
print('arr2 = ',arr2)

newarr1=np.concatenate((arr1, arr2))
newarr1

arr1 =  [['A' 'B']
 ['E' 'F']]
arr2 =  [['C' 'D']
 ['G' 'H']]


array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [53]:
# write your code here ^_^
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[['A' 'B']
  ['C' 'D']]

 [['E' 'F']
  ['G' 'H']]]


In [84]:
np.concatenate((arr1, arr2), axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [88]:
# write your code here ^_^
A1= np.split(newarr1,2,axis=1)
A1


[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]